"""Cooperative cancellation registry for in-flight chat turns, local to
this ai_agent process.

A turn runs synchronously inside this process's ask() tool call - there's
no way to reach into it and abort a network call already in flight. What
run_chat's tool-calling loop DOES already do is check something between
rounds, so a cheap process-wide flag checked at each of those points lets
a turn stop before its NEXT round rather than mid-call - bounded by one
round's latency, not instant, but far better than running the full loop
(up to max_tool_rounds billed calls) to completion after chat_app's caller has already
given up on it.

Keyed by an internal request_id generated by chat_app for each job,
never by the browser-supplied request_id, chat_id, or user. Each ai_agent
instance only ever tracks the turns it itself is serving.
"""

from __future__ import annotations

import threading

from src.catalog import catalog

_lock = threading.Lock()
_cancelled: set[str] = set()


@catalog
def register(request_id: str | None) -> None:
    """Preserve cancellation received while a turn was starting.

    Each job has a unique internal ID and clear() retires it on completion.
    Registration must not erase cancellation that raced with startup.
    """


@catalog
def cancel(request_id: str | None) -> bool:
    """Requests cancellation of the given turn. Returns False for a
    missing/empty id so the caller can tell "nothing to cancel" apart
    from "cancelled" without a separate lookup."""
    if not request_id:
        return False
    with _lock:
        _cancelled.add(request_id)
    return True


@catalog
def is_cancelled(request_id: str | None) -> bool:
    if not request_id:
        return False
    with _lock:
        return request_id in _cancelled


@catalog
def clear(request_id: str | None) -> None:
    """Removes a finished turn's entry so the set doesn't grow unbounded
    over the process lifetime. Safe to call whether or not the turn was
    ever actually cancelled."""
    if not request_id:
        return
    with _lock:
        _cancelled.discard(request_id)
