version: '3.8'
services:
  mcp_server:
    image: python:3.13-slim
    container_name: mcp-server
    volumes:
      - "/media/HDD320-1/MCPArchitecture/mcp_server:/app"
    working_dir: /app
    entrypoint: ["sh", "-c", "pip install . && python -m src.run"]
    restart: always
    ports:
      - "8010:8010"
    environment:
      MCP_HOST: "0.0.0.0"
      MCP_PORT: "8010"
      SMTP_PASSWORD: "@98paFne1jK23"
      SSH_HOST_KEY_POLICY: "reject"
