"""Cooperative cancellation registry for in-flight chat turns, local to
this ai_agent process.

A turn runs synchronously inside this process's ask() tool call - there's
no way to reach into it and abort a network call already in flight. What
run_chat's tool-calling loop DOES already do is check something between
rounds, so a cheap process-wide flag checked at each of those points lets
a turn stop before its NEXT round rather than mid-call - bounded by one
round's latency, not instant, but far better than running the full loop
(up to max_tool_rounds billed calls) to completion after chat_app's caller has already
given up on it.

Keyed by an internal request_id generated by chat_app for each job,
never by the browser-supplied request_id, chat_id, or user. Each ai_agent
instance only ever tracks the turns it itself is serving.

The bound turn also carries a shared event into worker threads. It survives
registry cleanup so a delegate still preparing when a deadline expires
inherits cancellation even if it links its child after the parent exits.
"""

from __future__ import annotations

import threading
from contextvars import ContextVar, Token

from src.core.catalog import catalog

_lock = threading.Lock()
_cancelled: set[str] = set()
_children: dict[str, set[str]] = {}
_signals: dict[str, threading.Event] = {}
_request: ContextVar[tuple[str | None, threading.Event] | None] = ContextVar("cancellation_request", default=None)


def bind_request(request_id: str | None) -> Token:
    """Carry the internal parent ID into tool worker threads."""
    with _lock:
        signal = _signals.setdefault(request_id, threading.Event()) if request_id else threading.Event()
        if request_id in _cancelled:
            signal.set()
    return _request.set((request_id, signal))


def reset_request(token: Token) -> None:
    _request.reset(token)


def current_request_id() -> str | None:
    bound = _request.get()
    return bound[0] if bound else None


def _cancel_tree(request_id: str) -> None:
    """Mark descendants while the registry lock is held."""
    pending = [request_id]
    seen: set[str] = set()
    while pending:
        current = pending.pop()
        if current in seen:
            continue
        seen.add(current)
        _cancelled.add(current)
        if signal := _signals.get(current):
            signal.set()
        pending.extend(_children.get(current, ()))


@catalog
def link(parent_id: str, child_id: str) -> None:
    """Link a delegate and preserve cancellation racing with its startup."""
    with _lock:
        _children.setdefault(parent_id, set()).add(child_id)
        bound = _request.get()
        if parent_id in _cancelled or (bound is not None and bound[0] == parent_id and bound[1].is_set()):
            _cancel_tree(child_id)


@catalog
def register(request_id: str | None) -> None:
    """Preserve cancellation received while a turn was starting.

    Each job has a unique internal ID and clear() retires it on completion.
    Registration must not erase cancellation that raced with startup.
    """


@catalog
def cancel(request_id: str | None) -> bool:
    """Requests cancellation of the given turn. Returns False for a
    missing/empty id so the caller can tell "nothing to cancel" apart
    from "cancelled" without a separate lookup."""
    if not request_id:
        return False
    with _lock:
        _cancel_tree(request_id)
    return True


@catalog
def is_cancelled(request_id: str | None) -> bool:
    if not request_id:
        return False
    with _lock:
        return request_id in _cancelled


@catalog
def clear(request_id: str | None) -> None:
    """Removes a finished turn's entry so the set doesn't grow unbounded
    over the process lifetime. Safe to call whether or not the turn was
    ever actually cancelled."""
    if not request_id:
        return
    with _lock:
        _cancelled.discard(request_id)
        _signals.pop(request_id, None)
        _children.pop(request_id, None)
        for parent, children in list(_children.items()):
            children.discard(request_id)
            if not children:
                del _children[parent]
