/** One chat turn as ai_agent's ask() expects it in `history`. */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

/** Live events ai_agent relays as MCP progress messages during ask(). */
export type AgentEvent =
  | { type: "token"; text: string }
  | { type: "token_reset" }
  | {
      type: "step_start";
      id: string;
      tool: string;
      label?: string;
      arguments: unknown;
    }
  | { type: "step_progress"; id: string; message: string }
  | { type: "step_end"; id: string; ok: boolean; result: string }
  | { type: "usage"; total_tokens: number; estimated: boolean };

/** ask()'s final result (only the fields ember_web uses so far). */
export interface AskResult {
  response: string;
  tools_used: string[];
  total_tokens: number | null;
  cancelled: boolean;
}

/** One mcp_server tool as the Tools page lists it. */
export interface ToolInfo {
  name: string;
  description: string;
  /** The tool's parameters as JSON Schema (pydantic-generated by FastMCP). */
  inputSchema: JsonSchema;
}

/** The subset of JSON Schema that tool parameter forms read. */
export interface JsonSchema {
  type?: string | string[];
  title?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
}

/** One mcp_server tool call's outcome as the Tools page shows it. */
export interface ToolRunResult {
  /** All text content parts, joined. */
  text: string;
  /** The tool reported failure (MCP isError), as opposed to a transport error. */
  isError: boolean;
  structured?: Record<string, unknown>;
}

/** One saved chat: its turns plus sidebar metadata. Times are epoch ms. */
export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}
