/** One message of a chat, as ember_api stores it. */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  /** summary: what the agent remembers of earlier messages; log_attachment:
   * the raw messages a summary or clear replaced (never sent to the agent);
   * command: a slash command and its result. */
  kind?: "summary" | "log_attachment" | "command";
  model?: string;
  total_tokens?: number;
  /** How full the agent's context was after this answer. */
  context_tokens?: number;
  context_window?: number;
}

/** Events of a turn ember_api runs, as its /events stream sends them. The
 * token/step ones are ai_agent's own, relayed. */
export type TurnEvent = { sequence: number } & (
  | { type: "snapshot"; text: string; activity: string }
  | { type: "token"; text: string }
  | { type: "token_reset" }
  | { type: "step_start"; id: string; tool: string; label?: string; arguments: unknown }
  | { type: "step_progress"; id: string; message: string }
  | { type: "step_end"; id: string; ok: boolean; result: string }
  | { type: "usage"; total_tokens: number; estimated: boolean }
  | { type: "summarizing" }
  | { type: "summarized" }
  | { type: "cancelling" }
  | { type: "final"; message: ChatMessage; cancelled: boolean }
  | { type: "error"; message: string }
);

/** One mcp_server resource, or a URI template (with {placeholders}). */
export interface ResourceInfo {
  uri: string;
  name: string;
  description: string;
  template: boolean;
}

/** One mcp_server tool as the Tools page lists it. */
export interface ToolInfo {
  name: string;
  /** Display title: the server's own title if it gives one, else derived from the name. */
  title: string;
  description: string;
  /** The tool's parameters as JSON Schema (pydantic-generated by FastMCP). */
  inputSchema: JsonSchema;
}

/** The subset of JSON Schema that tool parameter forms read. */
export interface JsonSchema {
  type?: string | string[];
  title?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
}

/** One mcp_server tool call's outcome as the Tools page shows it. */
export interface ToolRunResult {
  /** All text content parts, joined. */
  text: string;
  /** The tool reported failure (MCP isError), as opposed to a transport error. */
  isError: boolean;
  structured?: Record<string, unknown>;
}

/** One saved chat: its turns plus sidebar metadata. Times are epoch ms. */
export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  /** ai_agent id this chat last talked to; absent on chats saved before it existed. */
  agentId?: string;
  /** False until the transcript is fetched (the list comes without it). */
  messagesLoaded?: boolean;
  /** From the server's list, for chats whose messages aren't loaded yet. */
  messageCount?: number;
  /** ember_api is writing an answer for it right now. */
  running?: boolean;
  createdAt: number;
  updatedAt: number;
}

/** One registered ai_agent instance, as ember_api's GET /api/agents lists
 * it. No URL: the browser only reaches agents through ember_api's proxy. */
export interface AgentInfo {
  id: string;
  label: string;
}
