/** One mcp_server resource, or a URI template (with {placeholders}). */
export interface ResourceInfo {
  uri: string;
  name: string;
  description: string;
  template: boolean;
}

/** One mcp_server tool as the Tools page lists it. */
export interface ToolInfo {
  name: string;
  /** Display title: the server's own title if it gives one, else derived from the name. */
  title: string;
  description: string;
  /** The tool's parameters as JSON Schema (pydantic-generated by FastMCP). */
  inputSchema: JsonSchema;
}

/** The subset of JSON Schema that tool parameter forms read. */
export interface JsonSchema {
  type?: string | string[];
  title?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  format?: string;
  examples?: unknown[];
  minimum?: number;
  maximum?: number;
  maxLength?: number;
  pattern?: string;
  // Form hints a tool adds with Field(json_schema_extra=...), as chat_app's
  // command form reads them.
  /** Widget: text, textarea, password, number, range, date, select, checkbox, file. */
  input?: string;
  /** A path on mcp_server listing a select's options. */
  options_url?: string;
  /** The param whose value fills options_url's {placeholder}. */
  depends_on?: string;
  /** {param: option field}: filled in when an option is chosen. */
  sets?: Record<string, string>;
  /** {label: option field}: shown when an option is chosen. */
  shows?: Record<string, string>;
  /** Prefilled text; "{timestamp}" becomes the current time. */
  initial?: string;
  step?: number;
}

/** One mcp_server tool call's outcome as the Tools page shows it. */
export interface ToolRunResult {
  /** All text content parts, joined. */
  text: string;
  /** The tool reported failure (MCP isError), as opposed to a transport error. */
  isError: boolean;
  structured?: Record<string, unknown>;
}

